var <?=$name?>Options = <?=$layerOptions?>;

<?php if(isset($infoWindowFields) && count($infoWindowFields) > 0) { ?>
	var <?=$name?>InfoTemplate = new esri.InfoTemplate({
		content: "\
			<div id=\"<?=$name?>-info-template\">\
				<h2><?=$infoWindowTitle?></h2>\
				<table>\
					<?php foreach($infoWindowFields as $field) { ?>\
						<tr>\
							<td><?=$field?></td>\
							<td>${<?=$field?>}</td>\
						</tr>\
					<?php } ?>\
				</table>\
			</div>\
		"
	});
	<?=$name?>Options.infoTemplate = <?=$name?>InfoTemplate;
<?php } ?>

var <?=$name?>Layer;

<?php if(isset($extra)) { ?>
	<?=$extra?>
<?php } ?>

<?php if(isset($popupFields)) { ?>
	var <?=$name?>InfoTemplate = new esri.InfoTemplate({
		content: "\
			<div id=\"<?=$name?>-info-template\">\
				<h2><?=$infoWindowTitle?></h2>\
				<table>\
					<?php foreach($popupFields as $field => $fieldLabel) { ?>\
						<tr>\
							<td><?=$fieldLabel?></td>\
							<td>${<?=$field?>}</td>\
						</tr>\
					<?php } ?>\
				</table>\
			</div>\
		"
	});
	<?=$name?>Options.infoTemplate = <?=$name?>InfoTemplate;
<?php } ?>

var <?=$name?>AddLayer = function(){
	<?=$name?>Layer = new <?=$class?>(
		"<?=$endpoint?>",
		<?=$name?>Options
	);

	<?php if($hasQuery) { ?>
		<?=$name?>Layer.setDefinitionExpression(<?=$query['function']?>());
	<?php } ?>

	<?php if(isset($minScale)) { ?>
		<?=$name?>Layer.setMinScale(<?=$minScale?>);
	<?php } ?>

	map.addLayer(<?=$name?>Layer);
	
	<?php if($showLabels) { ?>
		var <?=$name?>LabelColor = "<?=(isset($layerOptions['color'])) ? $layerOptions['color'] : "#000"?>";
		var <?=$name?>Label = new esri.symbol.TextSymbol().setColor(new esri.Color(<?=$name?>LabelColor));

		var <?=$name?>LabelSize = "<?=(isset($layerOptions['size'])) ? $layerOptions['size'] : "8pt"?>";
		<?=$name?>Label.font.setSize(<?=$name?>LabelSize);

		var <?=$name?>LabelFont = "<?=(isset($layerOptions['font'])) ? $layerOptions['font'] : "arial"?>";
		<?=$name?>Label.font.setFamily(<?=$name?>LabelFont);

		var <?=$name?>LabelRenderer = new esri.renderer.SimpleRenderer(<?=$name?>Label);
		var <?=$name?>Labels = new esri.layers.LabelLayer({id: "<?=$name?>Labels"});
		
		var <?=$name?>LabelFormat = "<?=(isset($layerOptions['format']))
			? $layerOptions['format']
			: '${" + ' . $name . 'Options.outFields[0] + "}'
		?>";
		<?=$name?>Labels.addFeatureLayer(<?=$name?>Layer, <?=$name?>LabelRenderer, <?=$name?>LabelFormat);
		map.addLayer(<?=$name?>Labels);
		<?=$name?>Labels.setVisibility(<?=$visible ? 'true' : 'false'?>);
	<?php } ?>

	<?php if($showVisibilityToggle) { ?>
		<?php if($showLabels) { ?>
			addVisibilityToggle([<?=$name?>Layer, <?=$name?>Labels], '<?=$name?>', '<?=$label?>', <?=$visible ? 'true' : 'false'?>);
		<?php } else { ?>
			addVisibilityToggle([<?=$name?>Layer], '<?=$name?>', '<?=$label?>', <?=$visible ? 'true' : 'false'?>);
		<?php } ?>
	<?php } ?>
	<?=$name?>Layer.setVisibility(<?=$visible ? 'true' : 'false'?>);
};
<?=$name?>AddLayer();
