var <?=$name?>Options = <?=$layerOptions?>;

<?php if(isset($infoWindowFields) && count($infoWindowFields) > 0) { ?>
	var <?=$name?>InfoTemplate = new esri.InfoTemplate({
		content: "\
			<div id=\"<?=$name?>-info-template\">\
				<h2><?=$infoWindowTitle?></h2>\
				<table>\
					<?php foreach($infoWindowFields as $field) { ?>\
						<tr>\
							<td><?=$field?></td>\
							<td>${<?=$field?>}</td>\
						</tr>\
					<?php } ?>\
				</table>\
			</div>\
		"
	});
	<?=$name?>Options.infoTemplate = <?=$name?>InfoTemplate;
<?php } ?>

var <?=$name?>Layer;

<?php if(isset($extra)) { ?>
	<?=$extra?>
<?php } ?>

var <?=$name?>AddLayer = function(){
	<?=$name?>Layer = new <?=$class?>(
		"<?=$endpoint?>",
		<?=$name?>Options
	);

	<?php if($hasQuery) { ?>
		<?=$name?>Layer.setDefinitionExpression(<?=$query['function']?>());
	<?php } ?>

	<?php if(isset($minScale)) { ?>
		<?=$name?>Layer.setMinScale(<?=$minScale?>);
	<?php } ?>

	<?php if($showVisibilityToggle) { ?>
		addVisibilityToggle(<?=$name?>Layer, '<?=$name?>', '<?=$label?>', <?=$visible ? 'true' : 'false'?>);
	<?php } ?>
	<?=$name?>Layer.setVisibility(<?=$visible ? 'true' : 'false'?>);
	
	map.addLayer(<?=$name?>Layer);
	
	<?php if($showLabels) { ?>
		var <?=$name?>Label = new esri.symbol.TextSymbol().setColor(new esri.Color("<?=$labelOptions['color']?>"));
		<?=$name?>Label.font.setSize("<?=$labelOptions['size']?>");
		<?=$name?>Label.font.setFamily("<?=$labelOptions['font']?>");
		var <?=$name?>LabelRenderer = new esri.renderer.SimpleRenderer(<?=$name?>Label);
		var <?=$name?>Labels = new esri.layers.LabelLayer({id: "<?=$name?>Labels"});
		<?=$name?>Labels.addFeatureLayer(<?=$name?>Layer, <?=$name?>LabelRenderer, "<?=$labelOptions['format']?>");
		map.addLayer(<?=$name?>Labels);
	<?php } ?>
};
<?=$name?>AddLayer();
