<div id="<?=$name?>" class="widget ui-widget ui-corner-all border-box">
	<h2 class="ui-widget-header ui-corner-all"><?=$label?></h2>
	<div class="ui-widget-content">
		<table id="<?=$cssId?>" class="data-table">
			<thead>
				<tr>
					<?php foreach($data['columns'] as $column) { ?>
						<th><?=$column?></th>
					<?php } ?>
				</tr>
			</thead>
			<tbody>
				<?php foreach($data['data'] as $row) { ?>
					<tr class="<?=$this->widget->getClasses($row)?>">
						<?php foreach($row as $column => $value) { ?>
							<td class="<?=$column?>"><?=$value?></td>
						<?php } ?>
					</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
