<script type="text/javascript">
	google.load("visualization", "1", {packages: ["corechart"]});
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = new google.visualization.DataTable();
		<?php foreach($data['columns'] as $column => $dataType) { ?>
			data.addColumn('<?=$dataType?>', '<?=$column?>');
		<?php } ?>
		data.addRows([<?=\ATP\MapReduce::process(
			$data['data'],
			function($vals, $key) use ($data){
				$columnNames = array_keys($data['columns']);
				$keyName = $columnNames[0];
				$key = (strpos($data['columns'][$keyName], 'date') === false)
					? "'{$key}'"
					: "new Date('" . str_replace(" ", "T", $key) . "')";
				return "[{$key}, " . \ATP\MapReduce::wrapJoin($vals, ",") . "]";
			},
			new \ATP\Reducer\Concatenate(",")
		)?>]);
		
		var options = <?=$chartOptions?>;
		
		var chart = new google.visualization.LineChart(document.getElementById('<?=$cssId?>'));
		chart.draw(data, options);
	};
</script>
<div id="<?=$name?>" class="widget ui-widget ui-corner-all border-box">
	<h2 class="ui-widget-header ui-corner-all"><?=$label?></h2>
	<div class="ui-widget-content">
		<div id="<?=$cssId?>" class="chart"></div>
	</div>
</div>
