<?php $this->appendCss("/atp-viz/css/style.less")?>
<script type="text/javascript">
	dojo.require("esri.map");
	dojo.require("esri/toolbars/navigation");
	dojo.require("dijit/registry");
	dojo.require("esri/dijit/HomeButton");
	dojo.require("esri/dijit/BasemapToggle");
	dojo.require("esri/dijit/Legend");
	<?php foreach($requires as $req) { ?>
		dojo.require('<?=$req?>');
	<?php } ?>

	dojo.addOnLoad(function(){
		var map = new esri.Map("<?=$cssId?>",{
			center: [<?=$center['x']?>, <?=$center['y']?>],
			zoom: <?=$zoom?>,
			basemap: '<?=$baseMap?>'
		});
		
		var navToolbar = new esri.toolbars.Navigation(map);
		
		//on(navToolbar, "onExtentHistoryChange", extentHistoryChangeHandler);
	
		$(".zoomin").click(function () {
			navToolbar.activate(esri.toolbars.Navigation.ZOOM_IN);
		});

		$(".zoomout").click(function () {
			navToolbar.activate(esri.toolbars.Navigation.ZOOM_OUT);
		});

		$(".zoomfullext").click(function () {
			navToolbar.zoomToFullExtent();
		});

		$(".zoomprev").click(function () {
			navToolbar.zoomToPrevExtent();
		});

		$(".zoomnext").click(function () {
			navToolbar.zoomToNextExtent();
		});

		$(".pan").click(function () {
			navToolbar.activate(esri.toolbars.Navigation.PAN);
		});

		$(".deactivate").click(function () {
			navToolbar.deactivate();
		});

		function extentHistoryChangeHandler () {
			$(".zoomprev").disabled = navToolbar.isFirstExtent();
			$(".zoomnext").disabled = navToolbar.isLastExtent();
		}

		var toggleLayers = {};
		var addVisibilityToggle = function(layers, layerId, layerLabel, isVisible){
			var inputId = layerId + "VisibilityToggle";
			toggleLayers[inputId] = layers;
			
			//Create the checkbox if it doesn't exist
			if($("#" + inputId).length == 0) {
				var html = "<li><div>";
				html += "<input type=\"checkbox\" id=\"" + inputId + "\"";
				if(isVisible) html += " checked";
				html += "/>";
				html +=	"<label>" + layerLabel + "</label>";
				html += "</div></li>";
				$("div#<?=$name?> ul.visibility-toggles").append(html);
				$("div#<?=$name?> div.legend div.accordion").accordion("refresh");
			}
			
			//Unbind click event in case we are re-creating the layer
			$("#" + inputId).unbind('click');
			
			//Toggle layer visibility when checkbox clicked
			$("#" + inputId).click(function(){
				var checkbox = this;
				layers.forEach(function(layer){
					layer.setVisibility(checkbox.checked);
				});
			});
		};
		
		var disableToggles = function(){
			for(inputId in toggleLayers) {
				var item = $("#" + inputId).parent();
				if(toggleLayers[inputId][0].visibleAtMapScale) {
					item.removeClass("disabled");
					item.find("*").enable();
				} else {
					item.addClass("disabled");
					item.find("*").disable();
				}
				//alert(inputId);
			}
		};
		
		map.on("zoom-end", disableToggles);

		var legendLayers = [];
			
		<?=$layers?>
		
		var legend = new esri.dijit.Legend({
			map: map,
			layerInfos: legendLayers
		}, "legendDiv");
		legend.startup();
		
		disableToggles();
		
		<?php if(!empty($altBaseMap)) { ?>
			var toggle = new esri.dijit.BasemapToggle({map: map, basemap: "<?=$altBaseMap?>"}, "basemap-toggle");
			toggle.startup();
		<?php } ?>
		
		<?php if($showHomeButton) { ?>
			var home = new esri.dijit.HomeButton({map: map}, "home-button");
			home.startup();
		<?php } ?>
	});
</script>

<div id="<?=$name?>" class="widget map-widget ui-widget ui-corner-all border-box">
	<h2 class="ui-widget-header ui-corner-all"><?=$label?></h2>
	<div class="ui-widget-content">
		<div class="legend" <?php if(!$showLegend) { ?>style="display: none;"<?php } ?>>
			<div class="accordion">
				<h3>Show Layers</h3>
				<div>
					<ul class="visibility-toggles">
					</ul>
				</div>
				<h3>Legend</h3>
				<div id="legendDiv"></div>
			</div>
		</div>
		<div id="navToolbar" data-dojo-type="dijit/Toolbar">
			<div class="navButton zoomin">Zoom In</div>
			<div class="navButton zoomout">Zoom Out</div>
			<div class="navButton zoomfullext">Full Extent</div>
			<div class="navButton zoomprev">Prev Extent</div>
			<div class="navButton zoomnext">Next Extent</div>
			<div class="navButton pan">Pan</div>
			<div class="navButton deactivate">Deactivate</div>
		</div>
		<div id="<?=$cssId?>" class="map <?php if(!$showLegend) { ?>full-map<?php } ?>" data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center'">
			<div id="home-button"></div>
			<div id="basemap-toggle"></div>
		</div>
	</div>
</div>
